GAS_API_URL = "GAS API URL HERE"
LINE_API = "LINE Notify API KEY HERE"

GMAIL = "GOOGLE E-MAIL ADDRESS HERE"
G_PASS = "GOOGLE PASSWD HERE"
CHROME_DRIVER = "Chrome Driver Pass Here"
IS_HEADLESS = True
IS_DEBUG_MODE = True